#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

skip_tags: true

# branches to build, in case we want to whitelist or blacklist some
#branches:
#  only:
#    - /jm_.*/

# We'll probably want to filter branches and also have branch-conditional configs,
# at which point, look here: https://www.appveyor.com/docs/branches/

# skip commits with a commit message matching this regex
# note that [skip ci] and [skip appveyor] should work anyway
#skip_commits:
#  message: /\[chore\]/


#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2017

# scripts that are called at the very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

# Limit the number of revisions in the history and download as .zip file. Technically
# these seem to be mutually exclusive.
shallow_clone: true
clone_depth: 5

nuget:
  disable_publish_on_pr: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: x5HXnLkYkCzK7mWUW6O8QjNAaYNySKhI2Q20oah9i5mvnTk4U8jLJZnVb9MSxx0a

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch

matrix:
  fast_finish: true


#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration:
  - release

build:
  parallel: true

  # MSBuild verbosity level
  verbosity: normal


# NOTE : We don't set a custom build script, so by default AppVeyor builds with MSBuild, which is
# fine because that means between this and Travis CI, we're validating dotnet/msbuild and also
# Windows/MacOS/Linux.


before_build:
  # Make sure we have the right tools version
  - dotnet --version
  - dotnet restore

# scripts to run after build
after_build:


#---------------------------------#
#       tests configuration       #
#---------------------------------#

# Install tools needed for Code Coverage, run instrumented tests, and report coverage numbers
test_script:
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
  - nuget install coveralls.net -Version 0.8.0-unstable0013 -PreRelease -OutputDirectory tools

  # Run the netstandard tests.
  # Explicitly build with DebugType=Full specified. This means a non-portable, Windows-style PDB
  # will be generated, which OpenCover currently requires. We can stop doing this once OpenCover supports the new
  # portable PDB format.
  #
  # Also use -oldStyle flag which uses an alternate instrumentation hook that is available for .NET Core
  # Some comments on this can be found here: https://github.com/OpenCover/opencover/issues/601
  - .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:dotnet.exe -targetargs:"test --logger \"trx;LogFileName=netstandard_test_results.xml\" .\Keen.NetStandard.Test\Keen.NetStandard.Test.csproj /property:DebugType=Full" -mergeoutput -output:coverage.xml -filter:"+[*]* -[*.Test]* -[Moq*]*" -oldStyle -returntargetcode -register:user

  # Upload coverage results
  - .\tools\coveralls.net.0.8.0-unstable0013\tools\csmacnz.Coveralls.exe --opencover -i .\coverage.xml

  # Upload netstandard test results to appveyor
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\Keen.NetStandard.Test\TestResults\netstandard_test_results.xml))

#---------------------------------#
#         notifications           #
#---------------------------------#

# We should consider adding some notifications, e.g.:

#notifications:

  # Email
#  - provider: Email
#    to:
#      - user1@email.com
#      - user2@email.com
#    subject: 'Build {{status}}'                  # optional
#    message: "{{message}}, {{commitId}}, ..."    # optional
#    on_build_status_changed: true

  # Slack
#  - provider: Slack
#    incoming_webhook: http://incoming-webhook-url

  # ...or using auth token

#  - provider: Slack
#    auth_token:
#      secure: kBl9BlxvRMr9liHmnBs14A==
#    channel: development
#    template: "{message}, {commitId}, ..."
